site_name: Homelab


theme:
  name: material
  features:
    - navigation.top
    - navigation.tracking
    - navigation.tabs        # Top-level tabs
    - navigation.sections    # Sidebar grouping
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy      # Copy button for code blocks
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
  palette: 
    # Optional: Switch to dark mode automatically - this shit doesnt work idk how to fix it 
    - scheme: slate 
      primary: custom
      accent: custom
      # toggle:
      #   icon: material/brightness-4
      #   name: Switch to light mode
extra_css:
  - stylesheets/gruvbox.css
extra_javascript:
  - javascripts/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

### --- Markdown Extensions --- ###   
markdown_extensions:
  # Python Markdown's standard code highlighter
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  
  - admonition
  - pymdownx.details  # (Optional) Enables collapsible "???" blocks
  # "SuperFences" allows for nesting code blocks in lists, etc.
  - pymdownx.superfences
  # Enables the "Copy to Clipboard" button (optional but recommended)
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
# Your Topic-Based Structure
nav:
  - Home: index.md
  - Overview: overview/overview.md
  - Infrastructure:
    - Getting Started: 
      - PC Setup - App Server: infrastructure/gettingstarted/pcsetup.md
      - PC Setup - NAS: infrastructure/gettingstarted/nassetup.md
    - Filesystem & Storage: 
      - Management: infrastructure/filesystem/management.md
      - SnapRAID: infrastructure/filesystem/snapraid.md
      - MergerFS: infrastructure/filesystem/mergerfs.md
    - Docker: 
      - Overview: infrastructure/docker/docker.md
      - Cheat Sheet: infrastructure/docker/cheatsheet.md
    - git:
      - Git Basics: infrastructure/git/git.md
    - Shell: 
      - Zsh: infrastructure/shell/zsh.md
  - Networking & Access:
    - Pi-hole: services/pihole/pihole.md
    - Omada: services/omada/omada.md
    - Tailscale: services/tailscale/tailscale.md
    - NGINX Proxy Manager: networking/npm/overview.md
    - NPM & Pi-Hole: networking/npm/pihole.md
  - Monitoring: 
    - Homepage: monitoring/homepage.md
    - Dozzle: monitoring/dozzle.md
    - Uptime Kuma: monitoring/uptimekuma.md
    - Beszel: monitoring/beszel.md
  - Home Assistant: services/homeassisstant/homeassisstant.md
  - Cloud Services: 
    - Filebrowser: 
    - Nextcloud: services/nextcloud/nextcloud.md
    - Immich: 
      - Overview: services/immich/immich.md
      - Google Takeout Import: services/immich/takeoutimport.md
  - Media Server:
    - Arr Stack:
      - Radarr: services/servarr/radarr.md
      - Sonarr: services/servarr/sonarr.md
      - Prowlarr: services/servarr/prowlarr.md
    - qBittorrent: services/servarr/qbittorrent.md
  - Utilities: 
    - BentoPDF:
    - convertx: services/utilities/convertx.md
    - Obsidian LiveSync: services/utilities/obslivesync.md

